### ISSUE TITLE
CipherSpec.java:39-40: Add all constructors to reference...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/cactoos-crypto#3]
The puzzle `1-9c1906bd` from #1 has to be resolved:

https://github.com/g4s8/CryptoCactoos/blob/29edd81fee04e4c2912c7a49fb4adec7780d7433/src/main/java/org/cactoos/crypto/cipher/CipherSpec.java#L39-L40

The puzzle was created by g4s8 on 15-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
I'm not managing `g4s8/cryptocactoos` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
I'm not managing `g4s8/cactoss-crypto` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
I'm not managing `g4s8/cactoss-crypto` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/g4s8/cactoos-crypto/issues/3#issuecomment-373662991))

@g4s8 Job [#3](https://github.com/g4s8/cactoos-crypto/issues/3) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/g4s8/cactoos-crypto/issues/3#issuecomment-373782143))

@g4s8 Job [#3](https://github.com/g4s8/cactoos-crypto/issues/3) is already in scope

**Comment by 0crat** [comment]
The job [#3](https://github.com/g4s8/cactoos-crypto/issues/3) is now out of scope
